// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using x402dev.Database;

#nullable disable

namespace x402dev.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903114039_AddX402ApiLatency")]
    partial class AddX402ApiLatency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("x402dev.Database.Models.PublicMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asset")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payer")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaction")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublicMessages");
                });

            modelBuilder.Entity("x402dev.Database.Models.X402Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCheckDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastErrorDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextCheckDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJsonResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("X402Apis");
                });
#pragma warning restore 612, 618
        }
    }
}
